### ISSUE TITLE
Coloration syntaxique

### ISSUE THREAD

**Issue by anacaona83** [fedecbn/codex#1]
Comment fonctionne la coloration syntaxique des menus déroulants?

**Comment by TomMilon** [comment]
Si le menu déroulant est généré avec la fonction metaform_sel, il faut savoir que chaque éléments de ce menu déroulant (<option>) a pour class la même valeur que celle qui est affichée : 

```
"<option class='$value' >$value</option>"
```

D'autre part, dans le css global de l'application (_INCLUDE/css/eval.css) sont définit la coloration des ces classes. Par exemple : 

```
.UICN_DD {background-color:#CCCDCF;}
```
