### ISSUE TITLE
Onglet utilisateurs

### ISSUE THREAD

**Issue by anacaona83** [fedecbn/codex#2]
Comment ajouter un onglet utilisateurs à la rubrique syntaxa

**Comment by TomMilon** [comment]
Bonjour anacaona83,

Avant d'ajouter un onglet utilisateur, il est nécessaire de généraliser la partie 'ajout d'onglet' dans les différentes rubriques, chose qui a été réalisé pour plusieurs d’entre elles (notamment hub, lr, et refnat). Pour ce faire, regarde les commits correspondant : 
https://github.com/fedecbn/codex/commit/616b343afed4c943baf0473eb94c4b47c652e4d7
https://github.com/fedecbn/codex/commit/9e48a93c060426e0991a6beff53c50c99810af7a
La généralisation passe notamment par des modification de index.php et la modification de liste.php

Globalement, voici comment cela fonctionne : 
- le fichier liste.php récupère en méthod GET l'onget correspondant. En fonction, il récupèrer les info nécessaire et crée le json nécessaire pour créer la table.
- il faut ajouter la requête SQL à commun.inc.php pour les user (requête générique => on devrait l'ajouter à commun/commun.inc.php d'ailleurs)
- il faut également s'assurer que js/data.inc.js inclue en fin de script le js concernant les user.

Voilà,

Bon courage
